# This file is generated by setup.sh — do not edit manually.
# It captures the user's identity, platform, and selected scopes.
{
  username = "szymono";
  homeDirectory = "/home/szymono";
  isStandalone = false;

  scopes = [
    "shell"
    "python"
    "k8s_base"
    "k8s_dev"
    "pwsh"
    "oh_my_posh"
  ];
}
