{
  description = "Cross-platform user environment managed by home-manager";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { nixpkgs, home-manager, ... }:
    let
      # user-specific config generated by setup.sh
      config = import ./config.nix;

      mkHome = system: home-manager.lib.homeManagerConfiguration {
        pkgs = nixpkgs.legacyPackages.${system};
        modules = [ ./home.nix ];
        extraSpecialArgs = {
          inherit config;
        };
      };
    in
    {
      homeConfigurations = {
        "x86_64-linux" = mkHome "x86_64-linux";
        "aarch64-linux" = mkHome "aarch64-linux";
        "aarch64-darwin" = mkHome "aarch64-darwin";
      };
    };
}
