{ pkgs, config, lib, ... }:

let
  # user-specific config generated by setup.sh
  cfg = import ./config.nix;
in
{
  imports = [
    # scope option definition
    ./scopes/default.nix
    # scope modules — each self-activates based on scopes.enabled
    ./scopes/base.nix
    ./scopes/base_standalone.nix
    ./scopes/az.nix
    ./scopes/bun.nix
    ./scopes/conda.nix
    ./scopes/docker.nix
    ./scopes/gcloud.nix
    ./scopes/k8s_base.nix
    ./scopes/k8s_dev.nix
    ./scopes/k8s_ext.nix
    ./scopes/nodejs.nix
    ./scopes/oh_my_posh.nix
    ./scopes/pwsh.nix
    ./scopes/python.nix
    ./scopes/rice.nix
    ./scopes/shell.nix
    ./scopes/terraform.nix
    ./scopes/zsh.nix
  ];

  # apply user-specific settings
  home.username = cfg.username;
  home.homeDirectory = cfg.homeDirectory;
  home.stateVersion = "25.05";

  # apply enabled scopes from config
  scopes.enabled = cfg.scopes;
  scopes.isStandalone = cfg.isStandalone or false;

  # let home-manager manage itself
  programs.home-manager.enable = true;
}
