# -*- mode: ruby -*-
# vi: set ft=ruby :

# *Variables
provider     = "libvirt"
# network configuration
net_name = "vagrant-33"
# vm configuration
memory       = 2048
cpu          = 2

# *VMs spec
vm_boxes = {
  "rhel" => {
    :box => "generic/rhel8",
    :ip => "192.168.33.11",
    :script => <<~SCRIPT
      dnf install -y bash-completion
    SCRIPT
  },
  "centos" => {
    :box => "generic/centos8s",
    :ip => "192.168.33.12",
    :script => <<~SCRIPT
      dnf install -y ansible
    SCRIPT
  },
  "ubuntu" => {
    :box => "generic/ubuntu2204",
    :ip => "192.168.33.13",
    :script => <<~SCRIPT
      export DEBIAN_FRONTEND=noninteractive
      apt-add-repository -y ppa:ansible/ansible \\
        && apt-get update && apt-get install -qy ansible
    SCRIPT
  }
}

# *VM provisioning
Vagrant.configure("2") do |config|
  # common config
  config.vm.provider provider do |libvirt|
    libvirt.management_network_keep = true
    libvirt.memory = memory
    libvirt.cpus = cpu
  end
  vm_boxes.each do |key, value|
    ip_addr = value[:ip]
    hostname = "#{File.basename(Dir.pwd)}-#{key}".downcase
    config.vm.define key do |node|
      identity_file = "#{Dir.pwd}/.vagrant/machines/#{key}/#{provider}/private_key"
      # node triggers
      node.trigger.after :reload do |trigger|
        trigger.info = "Add vagrant configuration to ssh config file..."
        trigger.run = {
          privileged: "false", powershell_elevated_interactive: "false",
          path: "../../../.assets/trigger/set_ssh_config.ps1", :args => [ip_addr, hostname, identity_file]
        }
      end
      config.trigger.after :destroy do |trigger|
        trigger.info = "Cleaning up ssh config, known_hosts files and .vagrant directory..."
        trigger.run = {
          privileged: "false", powershell_elevated_interactive: "false",
          path: "../../../.assets/trigger/delete_ssh_config.ps1", :args => [ip_addr, hostname]
        }
      end
      # node setup
      node.vm.box = value[:box]
      node.vm.hostname = hostname
      node.vm.network :private_network,
        :ip => ip_addr,
        :libvirt__network_name => net_name,
        :libvirt__dhcp_enabled => false,
        :libvirt__always_destroy => false,
        :autostart => true
      # node provision
      node.vm.provision "shell", name: "run inline script...", inline: value[:script]
      node.vm.provision "ansible", playbook: "../../../.assets/playbooks/setup_user_ssh.yaml"
      node.vm.provision "ansible", playbook: "../../../.assets/playbooks/create_user.yaml"
      # ~reload vm
      node.vm.provision :reload
    end
  end
end
