# phase: scopes
# Load existing scopes, merge with CLI flags, resolve deps, write config.nix.
# Distinct from .assets/lib/scopes.sh (the shared scope-set library).
# shellcheck disable=SC2154  # globals set by bootstrap phase
#
# Reads:  CONFIG_NIX, any_scope, remove_scopes, omp_theme, starship_theme
# Writes: _scope_set, sorted_scopes, NIX_ENV_SCOPES, _ir_phase, _ir_error

phase_scopes_load_existing() {
  if [[ -f "$CONFIG_NIX" ]]; then
    if [[ "$any_scope" == "false" && ${#remove_scopes[@]} -eq 0 ]]; then
      info "no scope flags provided - loading scopes from config.nix..."
    else
      info "loading existing scopes from config.nix and merging with CLI flags..."
    fi
    local nix_eval_output nix_eval_rc
    nix_eval_output="$(_io_nix_eval '
      let cfg = import '"$CONFIG_NIX"';
      in builtins.concatStringsSep "\n" cfg.scopes
    ' 2>&1)"
    nix_eval_rc=$?
    if [[ $nix_eval_rc -eq 0 ]]; then
      local sc
      while IFS= read -r sc; do
        [[ -n "$sc" ]] && scope_add "$sc"
      done <<<"$nix_eval_output"
    else
      warn "failed to read config.nix: $nix_eval_output"
      if [[ ${#remove_scopes[@]} -gt 0 ]]; then
        _ir_error="cannot --remove scopes when config.nix is unreadable"
        err "$_ir_error"
        exit 1
      fi
    fi
  elif [[ "$any_scope" == "false" && ${#remove_scopes[@]} -eq 0 ]]; then
    info "no scope flags provided and no config.nix found - detecting from system..."
    command -v oh-my-posh &>/dev/null && scope_add oh_my_posh || true
    command -v docker &>/dev/null && scope_add docker || true
    { [[ -x "$HOME/.local/bin/uv" ]] || [[ -x "$HOME/.nix-profile/bin/uv" ]]; } && scope_add python || true
    command -v conda &>/dev/null && scope_add conda || true
  fi
}

phase_scopes_apply_removes() {
  if [[ ${#remove_scopes[@]} -gt 0 ]]; then
    validate_scopes "${remove_scopes[@]}" || exit 2
    local sc
    for sc in "${remove_scopes[@]}"; do
      if scope_has "$sc"; then
        scope_del "$sc"
        ok "removed scope: $sc"
      else
        warn "scope '$sc' is not currently configured - skipping"
      fi
    done
  fi
}

phase_scopes_enforce_prompt_exclusivity() {
  if [[ -n "$omp_theme" && -n "$starship_theme" ]]; then
    _ir_error="cannot use both --omp-theme and --starship-theme"
    err "$_ir_error"
    exit 2
  fi
  if [[ -n "$omp_theme" ]]; then
    scope_del starship
  elif [[ -n "$starship_theme" ]]; then
    scope_del oh_my_posh
  fi
}

phase_scopes_resolve_and_sort() {
  resolve_scope_deps
  sort_scopes
  NIX_ENV_SCOPES="${sorted_scopes[*]:-}"
  export NIX_ENV_SCOPES

  printf "\n\e[95;1m>> Dev Environment Setup via Nix (%s)\e[0m" "$platform"
  # shellcheck disable=SC2154  # sorted_scopes is populated by sort_scopes
  if ((${#sorted_scopes[@]} > 0)); then
    printf " : \e[3;90m%s\e[0m" "${sorted_scopes[*]}"
  fi
  printf "\n\n"
}

has_system_cmd() {
  local cmd_path
  cmd_path="$(command -v "$1" 2>/dev/null)" || return 1
  [[ "$cmd_path" != /nix/* && "$cmd_path" != */.nix-profile/* ]]
}

phase_scopes_detect_init() {
  is_init=false
  if ! has_system_cmd jq || ! has_system_cmd curl; then
    is_init=true
  fi
}

phase_scopes_write_config() {
  local nix_scopes=""
  local sc
  for sc in "${sorted_scopes[@]}"; do
    nix_scopes+="    \"$sc\""$'\n'
  done

  cat >"$CONFIG_NIX" <<EOF
# Generated by setup.sh -- do not edit manually.
# Re-run setup.sh with scope flags to change, or edit and run:
#   nix profile upgrade nix-env
{
  isInit = $is_init;

  scopes = [
$nix_scopes  ];
}
EOF

  info "generated config.nix with ${#sorted_scopes[@]} scopes"
}
