# -*- mode: ruby -*-
# vi: set ft=ruby :

# *Variables
box      = "generic/arch"
provider = "hyperv"
boxname  = "Arch"
# network configuration
nat_net  = "192.168.121.0/24"
ip_addr  = "192.168.121.56"
dns      = "9.9.9.9,149.112.112.112"
# vm configuration
memory   = 4096
cpu      = 4
# conditions
install_packages   = true
install_kubernetes = false
install_gnome      = false
install_edge       = false
setup_bash         = true
setup_pwsh         = true

# calculate global variables
vmname            = "Vg-#{boxname}"
hostname          = "#{vmname.downcase}-hv"
switch_ip, prefix = nat_net.sub(/0(?=\/)/, "1").split("/")
dns1, dns2        = dns.split(",")

# *Scripts
script_install_packages = <<~SCRIPT
  grep -qw '^Color' /etc/pacman.conf || sed -i 's/^#Color/Color/' /etc/pacman.conf
  pacman -Sy --needed --noconfirm btop nano
SCRIPT

script_configure_static_ip = <<~SCRIPT
  cat <<'EOF' >/etc/systemd/network/eth0.network
  [Match]
  Name=eth0

  [Network]
  Address=#{ip_addr}/#{prefix}
  Gateway=#{switch_ip}
  DNS=#{dns1}
  DNS=#{dns2}
  EOF
SCRIPT

script_install_psmodules = <<~SCRIPT
  pwsh -nop -c "@('aliases-git', 'do-common', 'do-linux') | ~/source/repos/szymonos/ps-modules/module_manage.ps1 -CleanUp" || true
SCRIPT

# *VM provisioning
Vagrant.configure("2") do |config|
  # common triggers
  config.trigger.before :up do |trigger|
    trigger.info = "Creating 'NATSwitch' Hyper-V switch if it does not exist..."
    trigger.run = {
      privileged: "true", powershell_elevated_interactive: "true",
      path: "../../../.assets/trigger/create_hyperv_natswitch.ps1", :args => [nat_net]
    }
  end
  # common config
  config.vm.network "public_network"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.define boxname do |node|
    identity_file = "#{Dir.pwd}/.vagrant/machines/#{boxname}/#{provider}/private_key"
    # node triggers
    node.trigger.before :reload do |trigger|
      trigger.info = "Setting Hyper-V switch to 'NATSwitch' to allow for static IP..."
      trigger.run = {
        privileged: "true", powershell_elevated_interactive: "true",
        path: "../../../.assets/trigger/set_hyperv_switch.ps1", :args => [vmname]
      }
    end
    node.trigger.after :reload do |trigger|
      trigger.info = "Add vagrant configuration to ssh config file..."
      trigger.run = {
        privileged: "false", powershell_elevated_interactive: "false",
        path: "../../../.assets/trigger/set_ssh_config.ps1", :args => [ip_addr, hostname, identity_file]
      }
    end
    config.trigger.after :destroy do |trigger|
      trigger.info = "Cleaning up ssh config, known_hosts files and .vagrant directory..."
      trigger.run = {
        privileged: "false", powershell_elevated_interactive: "false",
        path: "../../../.assets/trigger/delete_ssh_config.ps1", :args => [ip_addr, hostname]
      }
    end
    # node setup
    node.vm.box = box
    node.vm.hostname = hostname
    node.vm.provider provider do |h|
      h.vmname = vmname
      h.memory = memory
      h.maxmemory = memory
      h.cpus = cpu
      h.linked_clone = true
      h.enable_virtualization_extensions = true
    end
    # node provision
    node.vm.provision "shell", name: "configure static ip", inline: script_configure_static_ip
    node.vm.provision "shell", name: "upgrade system...", path: "../../../.assets/provision/upgrade_system.sh"
    node.vm.provision "shell", name: "install base...", path: "../../../.assets/provision/install_base.sh"
    if install_packages
      node.vm.provision "shell", name: "install packages...", inline: script_install_packages
      node.vm.provision "shell", name: "install exa...", path: "../../../.assets/provision/install_exa.sh", :args => '>/dev/null'
      node.vm.provision "shell", name: "install bat...", path: "../../../.assets/provision/install_bat.sh", :args => '>/dev/null'
      node.vm.provision "shell", name: "install ripgrep...", path: "../../../.assets/provision/install_ripgrep.sh", :args => '>/dev/null'
    end
    if install_kubernetes
      node.vm.provision "shell", name: "install yq...", path: "../../../.assets/provision/install_yq.sh", :args => '>/dev/null'
      node.vm.provision "shell", name: "install docker...", path: "../../../.assets/provision/install_docker.sh"
      node.vm.provision "shell", name: "install kubectl...", path: "../../../.assets/provision/install_kubectl.sh", :args => '>/dev/null'
      node.vm.provision "shell", name: "install kubelogin...", path: "../../../.assets/provision/install_kubelogin.sh", :args => '>/dev/null'
      node.vm.provision "shell", name: "install helm...", path: "../../../.assets/provision/install_helm.sh", :args => '>/dev/null'
      node.vm.provision "shell", name: "install minikube...", path: "../../../.assets/provision/install_minikube.sh", :args => '>/dev/null'
      node.vm.provision "shell", name: "install k3d...", path: "../../../.assets/provision/install_k3d.sh", :args => '>/dev/null'
      node.vm.provision "shell", name: "install k9s...", path: "../../../.assets/provision/install_k9s.sh", :args => '>/dev/null'
      node.vm.provision "shell", name: "install flux...", path: "../../../.assets/provision/install_flux.sh"
      node.vm.provision "shell", name: "install kubeseal...", path: "../../../.assets/provision/install_kubeseal.sh", :args => '>/dev/null'
      node.vm.provision "shell", name: "install kustomize...", path: "../../../.assets/provision/install_kustomize.sh"
      node.vm.provision "shell", name: "install argo-rollouts cli...", path: "../../../.assets/provision/install_argorolloutscli.sh", :args => '>/dev/null'
      node.vm.provision "shell", name: "install npm...", path: "../../../.assets/provision/install_npm.sh"
      node.vm.provision "shell", name: "install smee...", path: "../../../.assets/provision/install_smee.sh"
    end
    if install_gnome
      node.vm.provision "shell", name: "install Gnome...", path: "../../../.assets/provision/install_gnome.sh"
      node.vm.provision "shell", name: "set up Gnome...", path: "../../../.assets/provision/setup_gnome.sh", privileged: false
      node.vm.provision "shell", name: "install xrdp...", path: "../../../.assets/provision/install_xrdp.sh"
      if install_edge
        node.vm.provision "shell", name: "install Edge...", path: "../../../.assets/provision/install_edge.sh"
      end
    end
    if setup_bash || setup_pwsh
      node.vm.provision "file", source: "../../../.assets/config", destination: "$HOME/tmp/"
      node.vm.provision "shell", name: "install oh-my-posh...", path: "../../../.assets/provision/install_omp.sh", :args => '>/dev/null'
      node.vm.provision "shell", name: "set up oh-my-posh...", path: "../../../.assets/provision/setup_omp.sh"
    end
    if setup_bash
      node.vm.provision "shell", name: "set up bash for all users...", path: "../../../.assets/provision/setup_profile_allusers.sh"
      node.vm.provision "shell", name: "set up bash for current user...", path: "../../../.assets/provision/setup_profile_user.sh", privileged: false
    end
    if setup_pwsh
      node.vm.provision "shell", name: "install pwsh...", path: "../../../.assets/provision/install_pwsh.sh", :args => '>/dev/null'
      node.vm.provision "shell", name: "set up pwsh for all users...", path: "../../../.assets/provision/setup_profile_allusers.ps1"
      node.vm.provision "shell", name: "set up pwsh for current user...", path: "../../../.assets/provision/setup_profile_user.ps1", privileged: false
      node.vm.provision "shell", name: "clone ps-modules repo...", path: "../../../.assets/provision/setup_gh_repos.sh", :args => ['--repos', 'szymonos/ps-modules'], privileged: false
      node.vm.provision "shell", name: "install ps-modules...", inline: script_install_psmodules, privileged: false
    end
    # ~reload vm
    node.vm.provision :reload
  end
end
