name: Publish Docker image

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/**'
      - '.assets/**'
      - 'modules/**'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          path: linux-setup-scripts

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: linux-setup-scripts
          file: linux-setup-scripts/.assets/docker/Dockerfile
          push: true
          tags: muscimol/pwsh:latest
