name: Publish Docker image

on:
  push:
    branches:
      - 'main'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          path: linux-setup-scripts

      - name: Checkout the ps-modules repo
        uses: actions/checkout@v3
        with:
          repository: szymonos/ps-modules
          ref: main
          path: ps-modules

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: linux-setup-scripts/.assets/docker/Dockerfile
          push: true
          tags: muscimol/pwsh:latest
