name: Preflight Checks

on:
  pull_request:

jobs:
  preflight_checks:
    name: "pre-commit hooks"
    runs-on: ubuntu-slim

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Fetch base branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.11.6"
          enable-cache: "true"
          cache-dependency-glob: "uv.lock"

      - name: Sync uv virtual environment
        run: |
          uv sync --frozen --compile-bytecode

      - name: Build mkdocs documentation
        run: |
          uv run --frozen mkdocs build --strict

      - name: Run pre-commit hooks
        uses: j178/prek-action@v2
        with:
          extra-args: --from-ref "origin/${{ github.event.pull_request.base.ref }}" --to-ref HEAD
